### ISSUE TITLE
有关备份后恢复的问题

### ISSUE THREAD

**Issue by Qliangw** [kaedea/notion-up#2]
你好，请问：通过该脚本备份后，如何再原样导入？（目前我看到的是只能通过导出md文件逐层级的手动恢复）

**Comment by kaedea** [comment]
@Qliangw 
就我所知，目前 Notion 并没有提供导入自己数据库的功能，而且其提供的导入其他笔记的功能也非常鸡肋。
这个 Repo 的功能主要是用来保存被 Notion 同步丢了的笔记，以及查看每次同步之间文本变化（这两个功能 Notion 目前都非常糟糕）。
